### ISSUE TITLE
Request for Tiled and OBS Studio buttons

### ISSUE THREAD

**Issue by Quillraven** [Ruben35/More-Icons-unFold-Rainmeter#17]
Hi,

first of all BIG THANKS for this awesome content. It really improves the visual aspect of a desktop!

I saw that I am allowed to create issues to request new unfold areas, correct? If you have time, it would be great to add `Tiled` and `OBS Studio` as additional areas.

OBS is already available, which is okay. But OBS Studio would be great as addition.

Tiled is completely missing and I have no idea how to make these nice transparent white icons myself :( [Tiled](https://www.mapeditor.org/) is a well known map editor for 2d games. I guess any 2d game developer would be happy about that.

Let me know what you think! I starred the repository already ;)

**Comment by PinkDev1** [comment]
Sure thing! I'll add them asap.
And thanks for the star :D

After I do the pull request, I'll contact @Ruben35 to publish a new Release, since there's been plenty of commits since Release "unFold 3.0"

**Comment by Quillraven** [comment]
cool! thank you

**Comment by Ruben35** [comment]
If you have more request don't doubt to send them as issues ;) 
Both of you have a nice day!
