### ISSUE TITLE
Update edge browser icon

### ISSUE THREAD

**Issue by Quillraven** [Ruben35/More-Icons-unFold-Rainmeter#19]
Me again!

Thanks a lot for the new release - icons are already in use ;)
![image](https://user-images.githubusercontent.com/93260/79607012-d14ac280-80f2-11ea-8803-1350c3230a63.png)

Would it be possible to update the Edge browser icon to the correct new one? From what I know Microsoft released a new edge browser this year(?) and it has a new icon.

This is nothing urgent or critical. Just something for the future when there is time.

Thank you!

**Comment by Ruben35** [comment]
Hi @Quillraven! First of all thanks for using the icons! 🥇 
And thats a really good idea!
I will work for the new Microsft Edge button but i will add it as a new one because the previous browser stills alive haha 😆

I will let you know when the new "Micrsoft Edge Chromium" is ready 😄

**Comment by Ruben35** [comment]
Hi @Quillraven 😄 You can get the new Edge button as "EdgeChromium" on the repository, you can add the button on Rainmeter as [it is explained here ("the old way" steps)](https://github.com/Ruben35/More-Icons-unFold-Rainmeter#installation-wrench).

See you and thanks for your support!

**Comment by Quillraven** [comment]
cool - thanks a lot!
