### ISSUE TITLE
Request for more icons

### ISSUE THREAD

**Issue by sheldonfar** [Ruben35/More-Icons-unFold-Rainmeter#21]
Hey, thanks for cool icons!

Any chance you could add few more namely for Telegram, Slack, Toggl (those would be really nice to have as I use those apps a lot) and possibly Ccleaner, Postman and OpenVPN (totally not important but still mentioning)

Cheers

**Comment by Ruben35** [comment]
Sure @sheldonfar ! Thanks for using the icons! 😄 
I will notify you when they are ready! 👍

**Comment by PinkDev1** [comment]
I'm macking the Slack and Telegram icons rn

**Comment by Ruben35** [comment]
Hi @sheldonfar, now you can get the new buttons on the repository 🎉!

You can add the button on Rainmeter as [it is explained here ("the old way" steps)](https://github.com/Ruben35/More-Icons-unFold-Rainmeter#installation-wrench).

See you and thanks for your support! 
And thanks @PinkDev1 😄

**Comment by sheldonfar** [comment]
@Ruben35 @PinkDev1 Awesome job guys, thanks a lot!


P.s. My only remark is that it looks like you used old slack icon which they replaced a while ago with[ a new one](https://commons.wikimedia.org/wiki/File:Slack_icon_2019.svg). Any chance you could update that to match? Hope I'm not bothering you too much with that :)

**Comment by Ruben35** [comment]
@sheldonfar No problem! I'll will fix it!

**Comment by Ruben35** [comment]
@sheldonfar Done! Now, just download the new pngs on the folder "Buttons/Transparent", the .ini are the same :)
