### ISSUE TITLE
The icons do not show up when i click "load"

### ISSUE THREAD

**Issue by NotRippin** [Ruben35/More-Icons-unFold-Rainmeter#29]

**Comment by PinkDev1** [comment]
How did you install our icon pack? Did you use the rmskin file or install it manually?
Also, please add a screenshot of what the Rainmeter log says (Rainmeter->Manage->Open Log)
And tell us what version of Rainmeter, and wich version of our icon pack you're using.
![bruh](https://user-images.githubusercontent.com/46269721/84578877-a27e5f00-adb8-11ea-830d-2e66cacbb38e.png)

**Comment by PinkDev1** [comment]
Dead issue. @Ruben35, just close this
