### ISSUE TITLE
Suggestions for buttons! :)

### ISSUE THREAD

**Issue by Damo200** [Ruben35/More-Icons-unFold-Rainmeter#32]
iCUE Software - from Corsair
Aura Sync - from Asus
Xtreme Tuner (20 / 16 Series) - from Galax specifically has to be Xtreme Tuner not Xtreme Tuner Plus version 👍 
Fall Guys - from Steam
Wallpaper Engine from Steam 👍

**Comment by Ruben35** [comment]
Hi! I will let you know when they're ready.

**Comment by Damo200** [comment]
Thank you so much! 😃

**Comment by Ruben35** [comment]
Hi @Damo200!
Your request has been realized and you can find them on the repository or [in this commit](https://github.com/Ruben35/More-Icons-unFold-Rainmeter/commit/0edf80903f699c7061bc1048cf021048930d0ea9). 

Hope you enjoy them!
